In [6]:
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
df= pd.read_csv("salaries_and_fields_cleaned.csv")
df.head()

,Working_Year,Designation,Experience,Employment_Status,Employee_Location,Company_Size,Remote_Working_Ratio,Salary_USD
0,2020.0,Data Scientist,MI,FT,DE,L,0,6352272.0
1,2020.0,Principal Data Scientist,SE,FT,DE,M,100,130000.0
2,2020.0,Lead Data Engineer,SE,FT,NZ,S,50,125000.0
3,2020.0,Data Scientist,SE,FT,US,L,50,120000.0
4,2020.0,Data Scientist,MI,FT,US,M,100,118000.0

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15445 entries, 0 to 15444
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Working_Year          15445 non-null  float64
 1   Designation           15445 non-null  str
 2   Experience            15445 non-null  str
 3   Employment_Status     15445 non-null  str
 4   Employee_Location     15445 non-null  str
 5   Company_Size          15445 non-null  str
 6   Remote_Working_Ratio  15445 non-null  int64
 7   Salary_USD            15445 non-null  float64
dtypes: float64(2), int64(1), str(5)
memory usage: 965.4 KB

In [3]:
df.describe()

       Working_Year  Remote_Working_Ratio    Salary_USD
count  15445.000000          15445.000000  1.544500e+04
mean    2023.070767             34.260278  4.952062e+05
std        0.777236             46.864019  2.042122e+06
min     2020.000000              0.000000  1.400000e+04
25%     2023.000000              0.000000  1.043000e+05
50%     2023.000000              0.000000  1.450000e+05
75%     2024.000000            100.000000  1.950000e+05
max     2024.000000            100.000000  4.774170e+07

In [4]:
df.isna().sum()

Working_Year            0
Designation             0
Experience              0
Employment_Status       0
Employee_Location       0
Company_Size            0
Remote_Working_Ratio    0
Salary_USD              0
dtype: int64

In [7]:
df["Employment_Status"].value().count()

AttributeError: 'Series' object has no attribute 'value'

In [8]:
df.groupby("Experience").mean(numeric_only=True)

            Working_Year  Remote_Working_Ratio    Salary_USD
Experience
EN           2023.044498             35.881877  4.342133e+05
EX           2023.064240             40.042827  1.068245e+06
MI           2023.097982             31.372809  5.139848e+05
SE           2023.064054             34.878709  4.688487e+05

In [9]:
df.duplicated().sum()

np.int64(5756)

In [10]:
df.drop_duplicates(inplace=True)

In [11]:
sns.boxplot(df,x="Experience",y="Salary_usd")
plt.yscale("log")
plt.show()

ValueError: Could not interpret value `Salary_usd` for `y`. An entry with this name does not appear in `data`.